language: php
dist: trusty
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/resources

stages:
  - composer validate
  - test
  - test with coverage

before_install:
  - stty cols 130
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - .travis-scripts/cache-browscap.sh

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv $COMPOSER_FLAGS

script: php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --colors --columns 117 --verbose --no-coverage tests/phpbrowscapTest/BrowscapTest.php

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS=""

    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: test with coverage
      php: 7.1
      before_install:
        - stty cols 130
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
      script: php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --colors --columns 117 --verbose tests/phpbrowscapTest/BrowscapTest.php --coverage-text --coverage-clover=coverage.clover
      after_success:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.2/coveralls.phar && php -n coveralls.phar --verbose --coverage_clover=coverage.clover
        - bash <(curl -s https://codecov.io/bash) -f coverage.clover -F phpunit

    - stage: composer validate
      php: 7.1
      install: skip
      script: composer validate --strict

notifications:
  email: false
