language: php
sudo: false
dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/resources

stages:
  - composer validate
  - check coding style
  - test
  - test with coverage

before_install:
  - stty cols 130
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - .travis-scripts/cache-browscap.sh

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv $COMPOSER_FLAGS

script: php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --colors --columns 117 --verbose --no-coverage tests/phpbrowscapTest/BrowscapTest.php

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS=""

    - php: 5.4
      dist: trusty
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 5.4
      dist: trusty
      env: COMPOSER_FLAGS=""

    - php: 5.5
      dist: trusty
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 5.5
      dist: trusty
      env: COMPOSER_FLAGS=""

    - php: 5.6
      dist: xenial
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 5.6
      dist: xenial
      env: COMPOSER_FLAGS=""

    - php: 7.0
      dist: xenial
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 7.0
      dist: xenial
      env: COMPOSER_FLAGS=""

    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: test with coverage
      php: 7.1
      before_install:
        - stty cols 130
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
      script: php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --colors --columns 117 --verbose tests/phpbrowscapTest/BrowscapTest.php --coverage-text --coverage-clover=coverage.clover
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f coverage.clover -F phpunit

    - stage: composer validate
      php: 7.1
      install: skip
      script: composer validate --strict

    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: php -n -d memory_limit=768M vendor/bin/php-cs-fixer fix --dry-run -vv

notifications:
  email: false
