language: php
dist: trusty
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

os: linux

cache:
  directories:
  - $TRAVIS_BUILD_DIR/resources

before_script:
  - .travis-scripts/cache-browscap.sh
  - travis_retry composer self-update
  - travis_retry composer install -o --prefer-source

script: - php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --colors --verbose --exclude-group compare-with-native-function --coverage-text --coverage-clover=coverage.clover

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      dist: precise

    - stage: compare with native function
      php: 7.1
      script: php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --colors --verbose --group compare-with-native-function
